@startuml
start
if( interface bin not empty ) then
: Set State (Finished, ERROR_OUTPUT_NOT_EMPTY);
:  Go to AwaitCommand state;
end
endif
: Send To EspCam to Process current Picture;
if (There is no item) then
: Go to next bin;
: Go to auto_store state;
end
else if(There are Mixed Items) then
: Set State (Finished, ERROR_MIXED_ITEMS);
:  Go to AwaitCommand state;
end
endif
repeat : Get Bin that fits current number of items of processed type;
if(No Bin found) then
: map();
: Try finding a bin again;
if(No bin found again) then
: Set State (Finished, ERROR_FULL);
:  Go to AwaitCommand state;
end
endif
endif
: Read bin;
if(RFID mismatch) then
: map();
: Try finding a bin again;
if(No bin found again) then
: Set State (Finished, ERROR_FULL);
:  Go to AwaitCommand state;
end
endif
endif
: move bin to interface bin space;
: read and update weight;
repeat while (Items do not fit in bin) is (true)
: move conveyor;
: update bin with new items;
: read and update weight;
: store bin in storage;
: Go to auto_store state;
@enduml
