@startuml fetch
title MovementSystem::fetch

start
: STORE INITIAL POSITION
: MOVE FETCH_START OFFSET;
: EXTEND_PLATFORM FAST;
: GO TO INITIAL POSITION;
: MOVE FETCH_END OFFSET;
: RETRACT_PLATFORM SLOW;
: GO TO INITIAL POSITION;
end


@enduml

@startuml store
title MovementSystem::store

start
: STORE INITIAL POSITION;
: MOVE FETCH_END OFFSET;
: EXTEND_PLATFORM SLOW;
: GO TO INITIAL POSITION;
: MOVE FETCH_END OFFSET;
: RETRACT_PLATFORM FAST;
: GO TO INITIAL POSITION;
end


@enduml

@startuml read
title MovementSystem::read

start
: STORE INITIAL POSITION
: MOVE FETCH_START OFFSET;
: EXTEND_PLATFORM FAST;
: MOVE READ OFFSET;
: READ RFID;
: MOVE (- READ) OFFSET;
: RETRACT_PLATFORM FAST;
: GO TO INITIAL POSITION;
: RETURN RFID READ;
end


@enduml

@startuml read_fetch
title MovementSystem::read_fetch

start
: STORE INITIAL POSITION;
: MOVE FETCH_START OFFSET;
: EXTEND_PLATFORM FAST;
: MOVE READ OFFSET;
: READ RFID;
: MOVE (- READ) OFFSET;
if(RFID VALID) then
: GO TO INITIAL POSITION;
: MOVE FETCH_END OFFSET;
: RETRACT_PLATFORM SLOW;
: GO TO INITIAL POSITION;
: RETURN RFID READ;
end
else

: RETRACT_PLATFORM FAST;
: GO TO INITIAL POSITION;
: RETURN EMPTY;


end


@enduml