@startuml usecase
left to right direction
title Interface Use Cases
actor User

usecase "UC1. Connect to Sparts" as UC1
usecase "UC2. Search for Item (FR13.1)" as UC2
usecase "UC2.1. Search for Item by text (FR13.2)" as UC2.1
usecase "UC2.2. Search for Item by image (FR13.3)" as UC2.2
usecase "UC2.3 Show item information (FR13.4)" as UC2.3
usecase "UC3. Fetch bin  (FR13)" as UC3
usecase "UC4. Store Bin" as UC4
usecase "UC4.1. Update Bin Contents When Storing" as UC4.1
usecase "UC5. Read Bin Space (FR17)" as UC5
usecase "UC6. Remap (FR15, FR15.2)" as UC6
usecase "UC7. Reorganize (FR16)" as UC7
usecase "UC8. Automatic Storage (FR14)" as UC8
usecase "UC9. Prompt to Regorganize if needed (FR15.3)" as UC9
User --> UC8
User --> UC7
User --> UC6
User --> UC5
User --> UC4
User --> UC3
User --> UC2
User --> UC1

(UC2.1) .u.> (UC2): extend
(UC2.2) .u.> (UC2): extend
(UC2.3) .u.> (UC2): extend
(UC4.1) .u.> (UC4): extend
(UC9) .u.>(UC3):extend
(UC9) .u.>(UC5):extend
(UC9) .u.>(UC6):extend
(UC9) .u.>(UC8):extend
(UC9) .u.>(UC7):include


@enduml