@startuml Setup
participant Application
participant EmbeddedSystem
 
 activate EmbeddedSystem
 EmbeddedSystem -> EmbeddedSystem: start setup
 EmbeddedSystem -> EmbeddedSystem: Await Setup Config
 Application -> EmbeddedSystem: Send Setup
 note right
         Config
         ----
         "image_processing_uri" : "x.x.x.x:xxxx/image"
 end note

 deactivate EmbeddedSystem


EmbeddedSystem -> EmbeddedSystem: Parse Config
activate EmbeddedSystem
EmbeddedSystem -> EmbeddedSystem: Await Commands
Application -> EmbeddedSystem: Read Status "/status"
EmbeddedSystem --> Application: Status
Application -> EmbeddedSystem: Send Command
EmbeddedSystem -> EmbeddedSystem: Execute Command
Application -> EmbeddedSystem: Read Status "/status"
EmbeddedSystem --> Application: Status (RUNNING or IDLE and ERROR CODES)

@enduml


@startuml map
left to right direction
title Map 

[*] --> GoToBin : cur_bin = 0;
GoToBin: ENTRY / move_to(cur_bin);
GoToBin --> ScanBin
ScanBin: ENTRY / rfid = read_rfid()
ScanBin : EXIT / update_map(cur_bin,rfid)
ScanBin --> [*] : [cur_bin == LAST_BIN]
ScanBin --> GoToBin : [cur_bin < LAST_BIN] / cur_bin++;

@enduml

